name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
      - uses: "ramsey/composer-install@v1"
        run: composer test
